config/routes.rb
Rails.application.routes.draw do
  resources :teetimes

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

root :to => 'teetimes#landing_page'
  get '/signup' => 'users#new', as: :signup
  post '/users' => 'users#create'

end

app/models/teetime.rb
class Teetime < ActiveRecord::Base

  belongs_to :user

  # validates :date, presence: true
  validates :course, presence: true
COURSES = ['white course', 'black course', 'red course']
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :teetimes

  validates :email, presence: true, uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

# create a user and directly login if positive
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/teetimes'
    else
      redirect_to '/login'
    end
  end
# if not redirect back to login screen
  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end


  def user_params
    params.require(:user).permit(:email, :password)
  end
  # associated with the logout and will show you the login screen
end

app/controllers/teetimes_controller.rb
class TeetimesController < ApplicationController

    before_filter :authorize
# only signed in users can get to the /teetimes aspect of the sight

    def index
      @teetimes = Teetime.all
    end
# any teetime successfully made will be shoed in the index view
    def show
      @teetime = Teetime.find(params[:id])
# any distinct teetime can be individually displayed
    end

    def new
      @teetime = Teetime.new
    end
# you can make a new teetime that will be connected to index
#   can't create anythting without it being new
#     def create
#       @teetime = Teetime.new(teetime_params)
#
# # when a teetime is created it will display on the index
#       if @teetime.save
#         redirect_to teetimes_path, :alert => "Teetime made"
#       else
#         render "new"
#       end
#     end

  def create
    teetime = Teetime.new(teetime_params)
    if teetime.valid?
      current_user.teetimes.push teetime
      current_user.save
      redirect_to teetimes_path
    else
      flash["alert-warning"] = "Sorry, teetime not created"
      redirect_to new_teetime_path
    end
  end

  def edit
      @teetime = Teetime.find(params[:id])

    end

    def update
      @teetime = Teetime.find(params[:id])

      if @teetime.update_attributes(teetime_params)
        redirect_to teetimes_path, :alert => "Teetime changed!"
      else
        render "edit"
      end
    end

    def destroy
      @teetime = Teetime.find(params[:id])
      @teetime.destroy
      redirect_to teetimes_path

    end
# params are a pain  this makes them easier
    private
    def teetime_params
      params.require(:teetime).permit(:date, :time, :course)
    end

def landing_page
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
  end
# if a user succeeds in logging in he can have access throughout the sight
  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/teetimes' , notice: "You are now signed up"
    else
      redirect_to '/signup'
    end
  end

  private
# user_params defined. only a certified user can make a teetime
  def user_params
    params.require(:user).permit(:name, :email, :handicap, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teetimes_helper.rb
module TeetimesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= javascript_include_tag 'application.js' %>
  <link href='http://fonts.googleapis.com/css?family=Cinzel:700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <title>ForeSite</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>



  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
<div class="container-fluid">
<div class= "backdrop">
  <nav class="navbar navbar-default navbar-fixed-top">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <a class="navbar-brand" href="/login">ForeSite</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to  "Make a Teetime", new_teetime_path %></li>

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-cog" aria-hidden="true"> </span><span class="caret"></span>
            <ul class="dropdown-menu" role="menu">
              <!-- -->


              <li>
                <% if current_user %>
                    <%= link_to "Log out", logout_path %>
                <% else %>
                    <%= link_to "Login", login_path %>
                <% end %></li>

              <li>
                <% if current_user %>

                <% else %>
                  <li><%= link_to "Sign Up", signup_path %></li>
                <% end %>
        </li>


      </ul>
      </li>

    </div>

  </nav>




  <!--&lt;!&ndash;above puts access credentials throughout site&ndash;&gt;-->

</div>
<% flash.each do |key, value| %>
    <%= content_tag(:div, class: "alert alert-#{key}") do %>
        <p><%= value %></p>
    <% end %>
<% end %>



<%= yield %>




</div>
</div>
</body>
</html>

app/views/teetimes/edit.html.erb
<h1>CHANGE TEE TIME</h1>


<%= form_for @teetime do |f| %>
    <p>
      <%= f.label :date %>
      <%= f.text_field :date, id: "datepicker" %>
      <%= f.label :time %>
      <%= f.text_field :time %>
    </p>

    <p>
      <%= f.label :course %>
      <%= f.collection_select :course, Teetime::COURSES, :to_s, :to_s,
                              :include_blank => true%>
    </p>
<!--edit field that will change exixting teetime properties-->

    <p>
      <%= f.submit "Teetime Update" %>
    </p>
        <!--update submit will link back to main page through controller-->
<%end%>
<%= link_to "Back to listing",teetimes_path %>

<script>
    $(function() {
        $( "#datepicker" ).datepicker({ dateFormat: 'mm/dd/yy' });
    });
</script>

app/views/teetimes/index.html.erb
<!--all teetimes are listed and making a teetime is a click away-->
<div class="container Teetimes">
  <h1>People Looking for Someone to Play With</h1>
    <!--<img src=url("/Old-Course-St-Andrews-Links-Trust-2-960x390.jpg") alt="St.Andrews">-->
  <div class="container-fluid">

      <% @teetimes.each do |teetime| %>
            <h4>Name: <%= teetime.user.name%></h4>
            <h4>Email: <%= teetime.user.email %></h4>
             <h4>Handicap: <%= teetime.user.handicap %></h4>

            <h4>Date: <%=teetime.date %></h4>
            <h4>Teetime: <%=teetime.time %></h4>
            <h4>Course: <%=teetime.course%></h4>
        <p>
          <%= link_to "Show Teetime", teetime %> |
          <%= link_to "Change Teetime", edit_teetime_path(teetime)%>
        </p>
        <hr />
      <%end%>

  </div>
</div>
  <!--<hr>-->



  <!--<div ng-app="teetimesApp">-->
  <!--<div ng-controller="TeeTimesController as teetimes" ng-init="teetimes.getTeetimes()">-->
    <!--&lt;!&ndash;{{teetimes.Teetimes}}&ndash;&gt;-->

    <!--<body>-->
    <!--<ul>-->
      <!--<h2>Available Teetimes</h2>-->
      <!--<li-->
      <!--class="list-unstyled"-->
      <!--ng-repeat="teetime in teetimes.Teetimes"-->

      <!--ng-controller="TeetimesController"-->
      <!--id="container">-->


            <!--<span class="name">-->

             <!--<h3>   {{ teetime.user.name}}:-->
                <!--{{ teetime.date }}</h3>-->
                <!--{{ teetime.time }}</h3>-->
                <!--{{ teetime.course }}</h3>-->
  <!--</span>-->

      <!--</li>-->

    <!--</ul>-->

app/views/teetimes/landing_page.html.erb
<br>
<br>
<br>
<br>

<div class="cont x">

  <br>
    Find some one to tee up with
    You no longer have to walk on and get paired up with some rando.
    Foresite provides a listing of golfers looking to partner up with somebody at local courses.
    Post a teetime for the next time you are available to play or choose from the listings to arrange
    a teetime with one of your ForeSite friends.




</div>

app/views/teetimes/new.html.erb
<div class="new_teetime">
<h1> Make a Teetime</h1>


<h3>When do you want to play?</h3>

  <%= form_for @teetime do |f|%>
        <%= f.label :date %>
        <%= f.text_field :date, id: "datepicker" %>
        <%= f.label :time %>
        <%= f.text_field :time %>
<br>


    <h3> Participating Courses</h3>

    <p>
        <%= f.label :course %><br/>
      <%= f.collection_select :course, Teetime::COURSES, :to_s, :to_s,
                              :include_blank => true%>

    </p>
    <p>

        <%= f.submit "Make a Teetime" %>
    </p>
        <%= link_to "Back to listing",teetimes_path %>


<!--where the fun of the site should be  I failed at that-->
<%end%>
<script>
    $(function() {
        $( "#datepicker" ).datepicker({format: 'mm/dd/yyyy'});

    });

//   $(function() {
//        $( "#timepicker" ).timepicker();
//    });
</script>
</div>
<!--var date = $('#datepicker').datepicker({ dateFormat: 'dd-mm-yy' }).val();-->

app/views/teetimes/show.html.erb
<div class="container Teetimes">
  <h3>Players Name: <%= @teetime.user.name %></h3>
  <h3><%=@teetime.user.name%>'s Contact: <%= @teetime.user.email %></h3>
  <h3><%=@teetime.user.name%>'s Handicap: <%= @teetime.user.handicap %></h3>

    <h3><%= @teetime.date %></h3>
    <h3><%= @teetime.time %></h3>
    <h3><%= @teetime.course %></h3>

    <%= link_to "Back to listing",teetimes_path %>|
    <%= link_to "Cancel Teetime", @teetime, method: :delete, data: { confirm: "Do you really want to delete this????"} %>
  <br>
  <h3> Tell <%=@teetime.user.name%> you want to beat him in golf</h3>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Pick Teetime</button>

  <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
       An email has been sent to <%=@teetime.user.name%>
      </div>
    </div>
  </div>
</div>
<!--shows the teetime made-->

app/views/users/new.html.erb
<h1>Signup and find someone to golf with in no time</h1>
<div class="signup">
<%= form_for :user, url: '/users' do |f| %>

    Name: <%= f.text_field :name %>
    Handicap: <%= f.text_field :handicap %>
    Email: <%= f.text_field :email %><br>
    <br>
    Password: <%= f.password_field :password %>
    Password Confirmation: <%= f.password_field :password_confirmation %>
    </br>
    </br>
</div>
    <%= f.submit "Get Golfin" %>

<% end %>